
http:
  ip: "127.0.0.1"
  port: 8001
  read-timeout: 15
  write-timeout: 120
  cors:
    debug: true
    allowed-methods: ["GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE"]
    allowed-origins:
      - "http://localhost:3000"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "User-Agent"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
      - "OrganizationKey"
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"
   
